### PR TITLE
Use the CycloneDX Maven plugin to generate SBOMs

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Review by tsegismont — APPROVED** [review]
LGTM, thank you @jponge 

Does this make the SBOM  an artifact deployed to the Maven repository during the release?

**Comment by jponge** [comment]
Yes, it's attached to the deployment

**Comment by tsegismont** [comment]
@vietj we need to determine if this should be backported somehow to versions still maintained (3.9, 4.4, 4.5)

**Comment by vietj** [comment]
there is some thoughts necessary to define what we want to do for vertx 5 vs other and more changes potentially

**Pull request merged**
