### PR TITLE
Updated libraries versions

### PR DESCRIPTION
**Pull request by fmatar**

### CODE REVIEW

**Comment by purplefox** [comment]
Fady - have you signed the Eclipse CLA?

**Comment by fmatar** [comment]
I did ages ago. I don't know why it's requesting me to sign it again 

Sent from Outlook




On Sun, Jun 7, 2015 at 6:28 AM -0700, "Tim Fox" <notifications@github.com> wrote:












Fady - have you signed the Eclipse CLA?

**Comment by purplefox** [comment]
Yeah unfortunately the Eclipse CLA checker hook is a bit flaky and unreliable :(

**Comment by purplefox** [comment]
@vietj do you think upgrading these versions is ok?

**Pull request closed without merging**
